using Portfolio.Application.Tools.Extension;
using System.IO;

namespace Portfolio.Application.Models.Files
{
    public class FileDto
    {
        public Stream Content { get; set; }

        public string Name { get; set; }

        public string ContentType { get; set; }


        public string GetPathWithFileName(string typeBaseFolder, string folderName)
        {
            string uniqueAutoGeneratedFileName = Path.GetRandomFileName();
            string shortClientSideFileNameWithoutExt = Path.GetFileNameWithoutExtension(Name).TruncateLongString(10);
            string ext = Path.GetExtension(Name);
            string basePath = typeBaseFolder + "/" + folderName + "/";

            return basePath + uniqueAutoGeneratedFileName + "_" + shortClientSideFileNameWithoutExt + ext;
        }
    }
}
